server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: nestjs-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: nestjs-backend
          app: backend
          __path__: /pm2logs/CicsAppBackend-out-*.log
    pipeline_stages:
      - multiline:
          firstline: '^\[Nest\]'
          max_wait_time: 3s

  - job_name: nestjs-backend-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nestjs-backend
          app: backend
          stream: error
          __path__: /pm2logs/CicsAppBackend-error-*.log
    pipeline_stages:
      - multiline:
          firstline: '^\[Nest\]'
          max_wait_time: 3s
