import * as Knex from 'knex';

export async function seed(knex: Knex.Knex): Promise<any> {
  const data = [
    {
      career_code: 58,
      course_code: '028',
      semester: 1,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '169',
      semester: 1,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2666',
      semester: 1,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '119',
      semester: 1,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '177',
      semester: 1,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '216',
      semester: 1,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2792',
      semester: 1,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '029',
      semester: 2,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '170',
      semester: 2,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2667',
      semester: 2,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '072',
      semester: 2,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '178',
      semester: 2,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2793',
      semester: 2,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2797',
      semester: 3,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2795',
      semester: 3,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2796',
      semester: 3,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '290',
      semester: 3,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '146',
      semester: 3,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2794',
      semester: 3,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '949',
      semester: 4,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2798',
      semester: 4,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2799',
      semester: 4,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2800',
      semester: 4,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '085',
      semester: 4,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '291',
      semester: 4,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '292',
      semester: 4,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '147',
      semester: 4,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2801',
      semester: 4,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2802',
      semester: 5,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2803',
      semester: 5,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2804',
      semester: 5,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2805',
      semester: 5,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '077',
      semester: 5,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '673',
      semester: 5,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '674',
      semester: 5,
      field: 4,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '694',
      semester: 5,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2806',
      semester: 5,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '094',
      semester: 5,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2807',
      semester: 5,
      field: 5,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2808',
      semester: 6,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '685',
      semester: 6,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2809',
      semester: 6,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2810',
      semester: 6,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2811',
      semester: 6,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2812',
      semester: 6,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '904',
      semester: 6,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '905',
      semester: 6,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '670',
      semester: 6,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '779',
      semester: 6,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2670',
      semester: 6,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2813',
      semester: 7,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '795',
      semester: 7,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '950',
      semester: 7,
      field: 1,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2814',
      semester: 7,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2815',
      semester: 7,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2816',
      semester: 7,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2817',
      semester: 7,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '943',
      semester: 7,
      field: 3,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '919',
      semester: 7,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2818',
      semester: 7,
      field: 5,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2819',
      semester: 8,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2820',
      semester: 8,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2821',
      semester: 8,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2822',
      semester: 8,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2823',
      semester: 8,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '690',
      semester: 8,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2824',
      semester: 9,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2825',
      semester: 9,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2830',
      semester: 9,
      field: 1,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2826',
      semester: 9,
      field: 2,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2831',
      semester: 9,
      field: 2,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2827',
      semester: 9,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2832',
      semester: 9,
      field: 3,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2833',
      semester: 9,
      field: 3,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2828',
      semester: 9,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2672',
      semester: 9,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '922',
      semester: 9,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2570',
      semester: 9,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2829',
      semester: 9,
      field: 5,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2834',
      semester: 10,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2835',
      semester: 10,
      field: 1,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2838',
      semester: 10,
      field: 2,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2839',
      semester: 10,
      field: 2,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2836',
      semester: 10,
      field: 3,
      mandatory: true,
    },
    {
      career_code: 58,
      course_code: '2840',
      semester: 10,
      field: 3,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2841',
      semester: 10,
      field: 3,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2842',
      semester: 10,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '912',
      semester: 10,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '909',
      semester: 10,
      field: 4,
      mandatory: false,
    },
    {
      career_code: 58,
      course_code: '2837',
      semester: 10,
      field: 4,
      mandatory: true,
    },
  ];

  return knex('career_courses')
    .del()
    .then(() => {
      return knex('career_courses').insert(data);
    });
}
